### ISSUE TITLE
TP decomp licensing

### ISSUE THREAD

**Issue by Pheenoh** [Pheenoh/tp-licensing#1]
Hi!

You are mentioned here because you previously contributed to the [zeldaret/tp repo](https://github.com/zeldaret/tp), a decompilation of the game The Legend of Zelda: Twilight Princess

There is a move to license the source of that repo under [CC0](https://creativecommons.org/publicdomain/zero/1.0/), and for that we need your permission, as past contributors.

For more information: https://github.com/Pheenoh/tp-licensing/blob/main/README.md

If you don't care, the best choice to do for the project and users of the project (researchers, fans, modders...) is to agree.
If you agree, you can reply to this issue with some message like "I agree to share all my contributions to the tp decomp under CC0" 
If you disagree, please get in touch! Through [github issues](https://github.com/Pheenoh/tp-licensing/issues) or [discord]( https://discord.zelda64.dev)

**Comment by Pheenoh** [comment]
@TakaRikka @lepelog @hatal175 @Jcw87 @magcius @jdflyer @barzamin @Trueffeloot @Julgodis @notyourav @lioncash @DRK-512 @Yotona @tom-overton @Zen64 @kipcode66 @icogn @qwertyquerty @EpochFlame @Thar0

**Comment by Pheenoh** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by Trueffeloot** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by EpochFlame** [comment]
yeah sure cc0 is close enough to the unlicense, so I’m happy to have my contributions under public domain. unlicense would be preferable

cc0 is fine as well, I consent

**Comment by jdflyer** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by TakaRikka** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by RevoSucks** [comment]
Though I wasnt pinged, I agree to share all my contributions to the tp decomp under CC0.

This is because there's a couple of decomp.me scratches for TP which I have solved/contributed, but I didnt directly push to zeldaret/tp.

**Comment by icogn** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by Jcw87** [comment]
I have no disagreement with this. You may use my contributions under CC0.

**Comment by Yotona** [comment]
I consent for my contributions towards the tp decomp repository to be shared under the CC0 license.

**Comment by tom-overton** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by barzamin** [comment]
i agree to share all my contributions to the Twilight Princess decomp under CC0.

**Comment by hatal175** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by Julgodis** [comment]
I agree to share all my contributions to the Twilight Princess decomp under CC0.

**Comment by lioncash** [comment]
I agree to share all of my contributions under CC0

**Comment by qwertyquerty** [comment]
I agree to share all my contributions under CC0

**Comment by hytopoulos** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by Thar0** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by DRK-512** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by fulgurbloom** [comment]
I agree to share all my contributions to the tp decomp under CC0

**Comment by Pheenoh** [comment]
Thanks all for the quick responses! We have everybody's consent now 🎉
